# Generated by Django 3.0.7 on 2020-06-29 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, default='', max_length=150, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha y hora actual')),
                ('end_date', models.DateField(verbose_name='Selector de fecha')),
                ('note', models.TextField(blank=True, verbose_name='Nota')),
                ('attach', models.FileField(blank=True, upload_to='', verbose_name='Adjunto')),
                ('task', models.BooleanField(verbose_name='Tarea')),
                ('tag', models.CharField(max_length=40, verbose_name='Etiqueta')),
                ('type', models.CharField(choices=[('A', 'Ejemplo 1'), ('B', 'Ejemplo 2')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CORE.UserNote')),
            ],
        ),
    ]
